services:
  app:
    container_name: flask
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./back:/app
    # env_file:
    #   - .env
    init: true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  db:
    container_name:  sqlite
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./db:/data
    working_dir: /data
    command: tail -f /dev/null

  svelte:
    container_name: svelte
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./front/app:/usr/src/app
    command: npm run dev -- --open
    tty: true
    ports:
      - "3000:3000"
      