version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///data/attendance.db
    depends_on:
      - db
    
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    container_name: database
    image: alpine:latest
    volumes:
      - ./data:/data
    command: ["sh", "-c", "mkdir -p /data && touch /data/attendance.db && tail -f /dev/null"]

volumes:
  data: