version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/data
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////data/attendance.db
    depends_on:
      db:
        condition: service_started
    
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    container_name: database
    image: alpine:latest
    volumes:
      - ./data:/data
    command: ["sh", "-c", "mkdir -p /data && touch /data/attendance.db && tail -f /dev/null"]
    healthcheck:
      test: ["CMD", "test", "-f", "/data/attendance.db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data: